# .github/workflows/main.yml
name: 🚀 Deploy auto-run_app
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: ${{ secrets.GCP_PROJECT_ID }}
  EMAIL: github-actions@gcloudautodeploy.iam.gserviceaccount.com
  REGION: southamerica-east1

jobs:
  deploy:
    name: Deploying 🚀 Auto-deploy app
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy please')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: $EMAIL
          project_id: $PROJECT_ID

      - name: Building (🏗)
        run: |-
          gcloud builds submit \
            --tag gcr.io/$PROJECT_ID/$APP_ID
        #run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      # Setup gcloud CLI
      - name: Deploy (🚀)
        uses: google-github-actions/deploy-cloudrun@master
        with:
          service: SERVICE_ID
          image: gcr.io/$PROJECT_ID/$APP_ID
          region: $REGION
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: $PROJECT_ID

